name: senai_iot_monitoring_api
description: Projeto focado no uso do dart, usando o shelf como criado de api
version: 0.3.0
# repository: https://github.com/GetuliovmSantos/senai-iot-monitoring-api

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
